version: '3.8'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - '5432:5432'
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      - PYTHONPATH=${PYTHONPATH}:/app
    env_file:
      - .env
    depends_on:
      - db
volumes:
    postgres_data: