"""add columns to blog

Revision ID: 050cc978aa05
Revises: da8e3b4860ad
Create Date: 2022-01-15 07:33:15.685907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050cc978aa05'
down_revision = 'da8e3b4860ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('body', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'body')
    # ### end Alembic commands ###
