"""remove columns from blog

Revision ID: 2a5f457c546b
Revises: 050cc978aa05
Create Date: 2022-01-15 07:35:10.780479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5f457c546b'
down_revision = '050cc978aa05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
