"""add columns to blog

Revision ID: da8e3b4860ad
Revises: 0eef827b341f
Create Date: 2022-01-15 07:30:54.172012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8e3b4860ad'
down_revision = '0eef827b341f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
